### ISSUE TITLE
Google Finance Issue

### ISSUE THREAD

**Issue by ArjunWhabi** [constverum/Quantdom#10]
Hi my installation is succesful:

Successfully installed PyQt5-5.12 PyQt5-sip-4.19.14 certifi-2018.11.29 chardet-3.0.4 idna-2.8 lxml-4.3.1 numpy-1.16.1 pandas-0.24.1 pandas-datareader-0.7.0 pyqtgraph-0.10.0 python-dateutil-2.8.0 pytz-2018.9 quantdom-0.1 requests-2.21.0 six-1.12.0 urllib3-1.24.1 wrapt-1.11.1

But when I type quantdom in the cmd prompt. It launches for a minute. When I click on 'Load' to load the data, gives following error:

(quantdom) D:\WinPython-3670>quantdom
qt.qpa.fonts: Unable to open default EUDC font: "EUDC.TTE"
Traceback (most recent call last):
  File "d:\winpython-3670\quantdom\lib\site-packages\quantdom\ui.py", line 185, in update_data
    date_to=self.date_to,
  File "d:\winpython-3670\quantdom\lib\site-packages\quantdom\lib\loaders.py", line 123, in get_quotes
    quotes = loader.get_quotes(*args, **kwargs)
  File "d:\winpython-3670\quantdom\lib\site-packages\quantdom\lib\utils.py", line 52, in wrapper
    res = fn(*args, **kwargs)
  File "d:\winpython-3670\quantdom\lib\site-packages\quantdom\lib\loaders.py", line 66, in get_quotes
    quotes = cls._get(symbol, date_from, date_to)
  File "d:\winpython-3670\quantdom\lib\site-packages\quantdom\lib\loaders.py", line 90, in _get
    return get_data_google(symbol, date_from, date_to)
  File "d:\winpython-3670\quantdom\lib\site-packages\pandas_datareader\data.py", line 66, in get_data_google
    return GoogleDailyReader(*args, **kwargs).read()
  File "d:\winpython-3670\quantdom\lib\site-packages\pandas_datareader\google\daily.py", line 36, in __init__
    raise ImmediateDeprecationError(DEP_ERROR_MSG.format('Google finance'))
pandas_datareader.exceptions.ImmediateDeprecationError:
Google finance has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.

**Comment by constverum** [comment]
Thank you! Fixed in v. 0.1.1
