### ISSUE TITLE
ModuleNotFoundError: No module named 'quantdom.lib'

### ISSUE THREAD

**Issue by qg0** [constverum/Quantdom#2]
All dependencies is satisfied:
Python 3.6 or higher
PyQt5
PyQtGraph
NumPy
requirements.txt

```
(.env) ➜  quantdom
Traceback (most recent call last):
  File "/root/desktop/.env/bin/quantdom", line 11, in <module>
    load_entry_point('quantdom==0.1a1', 'console_scripts', 'quantdom')()
  File "/root/desktop/.env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/root/desktop/.env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/root/desktop/.env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/root/desktop/.env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/desktop/.env/lib/python3.6/site-packages/quantdom/__init__.py", line 29, in <module>
    from .ui import *  # noqa
  File "/root/desktop/.env/lib/python3.6/site-packages/quantdom/ui.py", line 10, in <module>
    from .lib import (  # noqa
ModuleNotFoundError: No module named 'quantdom.lib'
```

**Comment by constverum** [comment]
Fixed in v0.1
